### ISSUE TITLE
sdkv2 What version required on Homey?

### ISSUE THREAD

**Issue by Steefph** [athombv/com.qubino#25]
I would like to try and run the sdkv2 rebuild (especially to try and use the i2 and i3 on the zmnhda2 (if possible)) but, when trying to perform the load it directly crashes. 
The Homey is running 1.5.5 and the error is as below. Is this due to 1.5.5?

2017-11-20 14:31:48 [log] [QubinoApp] com.qubino running...
/node_modules/homey-meshdriver:1
(function (exports, require, module, __filename, __dirname) { ../../../node-homey-meshdriver
                                                              ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/drivers/ZMNHDA2/device.js:3:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
    at require (internal/module.js:11:18)
    at fs.stat (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:3769)
    at FSReqWrap.oncomplete (fs.js:153:5)

Would like to continue using Homey for switching scenes via I2 and I3 (don't want to rebuild everything on my Zipabox :) )

**Comment by RobinBol** [comment]
SDKv2 is support from 1.5.0 and up, but that branch is a development branch and will not work. When the features are done they will be released in the app store!
